# 1. Exercise on Functions:

## Task - 1:

Create a Python program that converts between different units of measurement.

• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.

• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [ ]:
def length_convert(value, unit):
    if unit == 'm':
        return value * 3.28084
    elif unit == 'ft':
        return value / 3.28084
    else:
        raise ValueError("Invalid unit for conversion.")

def weight_convert(value, unit):
    if unit == 'kg':
        return value * 2.20462  #kg to lbs
    elif unit == 'lbs':
        return value / 2.20462  #lbs to kg
    else:
        raise ValueError("Invalid unit for weight conversion.")

def volume_convert(value, unit):
    if unit == 'L':
        return value * 0.264172  #liters to gallons
    elif unit == 'gal':
        return value / 0.264172  #gallons to liters
    else:
        raise ValueError("Invalid unit for conversion.")

def main():
    print("Unit Converter: ")
    print("1. Length (Meters to Feet)")
    print("2. Weight (Kilograms to Pounds)")
    print("3. Volume (Liters to Gallons)")

    try:
        input = int(input("Choose a conversion type (1/2/3): "))
        value = float(input("Enter the number to convert: "))

        if input == 1:
            unit = input("Enter the unit (m or ft): ").strip().lower()
            converted_value = length_convert(value, unit)
            print(f"Converted Value: {converted_value:.4f}")
        elif input == 2:
            unit = input("Enter the unit (kg or lbs): ").strip().lower()
            converted_value = weight_convert(value, unit)
            print(f"Converted Value: {converted_value:.4f}")
        elif input == 3:
            unit = input("Enter the unit (L or gal): ").strip().lower()
            converted_value = volume_convert(value, unit)
            print(f"Converted Value: {converted_value:.4f}")
        else:
            print("Invalid choice. Please select 1, 2, or 3.")
    except ValueError as e:
        print(f"Error: {e}. Please enter valid numeric values and units.")
    except Exception as e:
        print(f"Unexpected error: {e}")

if __name__ == "__main__":
    main()

Unit Converter: 
1. Length (Meters to Feet)
2. Weight (Kilograms to Pounds)
3. Volume (Liters to Gallons)
Choose a conversion type (1/2/3): 1
Enter the number to convert: 20
Enter the unit (m or ft): ft
Converted Value: 6.0960


## Task - 2:

Create a Python program that performs various mathematical operations on a list of numbers.

• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).

3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [ ]:
def calculate_sum(num):
    return sum(num)

def calculate_average(num):
    return sum(num) / len(num) if num else 0

def find_maximum(num):
    return max(num)

def find_minimum(num):
    return min(num)

def main():
    print("Choose an Operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        operation = int(input("Choose an operation (1/2/3/4): "))  # Renamed from 'input' to 'choice'
        num = list(map(float, input("Enter numbers separated by spaces: ").split()))

        if not num:
            raise ValueError("The list cannot be empty.")

        if operation == 1:
            result = calculate_sum(num)
        elif operation == 2:
            result = calculate_average(num)
        elif operation == 3:
            result = find_maximum(num)
        elif operation == 4:
            result = find_minimum(num)
        else:
            print("Invalid choice. Please select 1, 2, 3, or 4.")
            return

        print(f"Result: {result}")
    except ValueError as e:
        print(f"Error: {e}. Please enter valid numbers.")
    except Exception as e:
        print(f"Unexpected error: {e}")

if __name__ == "__main__":
    main()

Choose an Operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Choose an operation (1/2/3/4): 4
Enter numbers separated by spaces: 10 99 68 109
Result: 10.0


# 2. Exercise on List Manipulation:

1. Extract Every Other Element:

Write a Python function that extracts every other element from a list, starting from the first element.

• Requirements:

– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def extract_list(lst):
    return lst[::2]  #slicing with step 2 to get every other element

input_list = [1, 2, 3, 4, 5, 6]
output_list = extract_list(input_list)
print("Original List:",input_list)
print("New List:",output_list)

Original List: [1, 2, 3, 4, 5, 6]
New List: [1, 3, 5]


**2**. Slice a Sublist:

Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

• Requirements:

– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).

– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [ ]:
def sublist(lst, start, end):
    return lst[start:end+1]  #slicing from start to end (inclusive)

input_list = [1, 2, 3, 4, 5, 6]
start_index = 2
end_index = 4

output_list = sublist(input_list, start_index, end_index)

print(f"Original List: {input_list}")
print(f"Sublist from index {start_index} to {end_index} is: {output_list}")

Original List: [1, 2, 3, 4, 5, 6]
Sublist from index 2 to 4 is: [3, 4, 5]


3. Reverse a List Using Slicing:

Write a Python function that reverses a list using slicing.

• Requirements:

– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverse_list(lst):
    return lst[::-1]  #slicing with -1 to reverse the list

input_list = [1, 2, 3, 4, 5]
output_list = reverse_list(input_list)

print("Original List:",input_list)
print("Reversed List:",output_list)

Original List: [1, 2, 3, 4, 5]
Reversed List: [5, 4, 3, 2, 1]


4. Remove the First and Last Elements:

Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

• Requirements:

– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def remove_first_last(lst):
    return lst[1:-1]  #slicing to remove first and last elements

input_list = [1, 2, 3, 4, 5]
output_list = remove_first_last(input_list)

print("Original List:",input_list)
print("New List:",output_list)

Original List: [1, 2, 3, 4, 5]
New List: [2, 3, 4]


5. Get the First n Elements:

Write a Python function that extracts the first n elements from a list.

• Requirements:

– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.

– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def first_n(lst, n):
    return lst[:n]  #slicing to get the first n elements

input_list = [1, 2, 3, 4, 5]
n = 3
output_list = first_n(input_list, n)

print(f"Original List: {input_list}")
print(f"First {n} Elements: {output_list}")

Original List: [1, 2, 3, 4, 5]
First 3 Elements: [1, 2, 3]


6. Extract Elements from the End:

Write a Python function that extracts the last n elements of a list using slicing.

• Requirements:

– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.

– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def last_n(lst, n):
    return lst[-n:]  #slicing to get the last n element

input_list = [1, 2, 3, 4, 5]
n = 2
output_list = last_n(input_list, n)

print(f"Original List: {input_list}")
print(f"Last {n} Elements: {output_list}")

Original List: [1, 2, 3, 4, 5]
Last 2 Elements: [4, 5]


7. Extract Elements in Reverse Order:

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

• Requirements:

– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
def reverse_skip(lst):
    return lst[-2::-2]  #start from second-to-last, move backward skipping one element

input_list = [1, 2, 3, 4, 5, 6]
output_list = reverse_skip(input_list)

print("Original List:",input_list)
print("Reversed & Skipped List:",output_list)

Original List: [1, 2, 3, 4, 5, 6]
Reversed & Skipped List: [5, 3, 1]


# 3. Exercise on Nested List:

1. Flatten a Nested List:

Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

• Requirements:

– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.

– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [ ]:
def flatten(lst):
    flat_list = [] #initialize empty list
    for sublist in lst:
        flat_list.extend(sublist)  #combines main list with elements from sublists
    return flat_list

input_list = [[1, 2], [3, 4], [5]]
output_list = flatten(input_list)

print("Original Nested List:", input_list)
print("Flattened List:", output_list)

Original Nested List: [[1, 2], [3, 4], [5]]
Flattened List: [1, 2, 3, 4, 5]


2. Accessing Nested List Elements:

Write a Python function that extracts a specific element from a nested list given its indices.

• Requirements:

– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.

– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [ ]:
def access_nested_element(lst, indices):
    try:
        element = lst
        for index in indices:
            element = element[index]  #iterate through the nested list
        return element
    except (IndexError, TypeError):
        return "Invalid indices or structure."

nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]  #extracting element at row[1] col[2]

result = access_nested_element(nested_list, indices)
print("Nested List:",nested_list)
print("Indices:",indices)
print("Output:",result)

Nested List: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Indices: [1, 2]
Output: 6


3. Sum of All Elements in a Nested List:

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

• Requirements:

– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
def sum_nested(lst):
    total = 0  #initialize the sum

    for element in lst:
        if isinstance(element, list):
            total += sum_nested(element)  #add nested list elements recursively
        else:
            total += element
    return total

nested_list = [[1, 2], [3, [4, 5]], 6]
sum_list = sum_nested(nested_list)
print("Nested List:",nested_list)
print("Sum of Nested List:",sum_list)

Nested List: [[1, 2], [3, [4, 5]], 6]
Sum of Nested List: 21


4. Remove Specific Element from a Nested List:

Write a Python function that removes all occurrences of a specific element from a nested list.

• Requirements:

– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.

– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [ ]:
def remove_element(lst, elements):
    result = [] #initialize empty list
    for item in lst:
        if isinstance(item, list): #check if the item is a nested list
            sublist = remove_element(item, elements) # process the nested list recursively
            if sublist:  #only append non-empty lists to the result
                result.append(sublist)
        elif item != elements: #keep the item if is not the element to be removed
            result.append(item)
    return result

input_list = [[1, 2], [3, 2], [4, 5]]
elements = 2
new_list = remove_element(input_list, elements)

print("Original List:",input_list)
print("New List:",new_list)

Original List: [[1, 2], [3, 2], [4, 5]]
New List: [[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:

Write a Python function that finds the maximum element in a nested list (regardless of depth).

• Requirements:

– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def find_max(lst):
    max_value = float('-inf')  #initialize value with negative infinity to handle any number

    for item in lst:
        if isinstance(item, list):  #recursively find maximum element
            max_value = max(max_value, find_max(item))
        else:  #if item is a number, compare with max_value
            max_value = max(max_value, item)
    return max_value

input_list = [[1, 2], [3, [4, 5]], 6]
maximum_element = find_max(input_list)

print("Original List:",input_list)
print("Maximum Element:",maximum_element)

Original List: [[1, 2], [3, [4, 5]], 6]
Maximum Element: 6


6. Count Occurrences of an Element in a Nested List:

Write a Python function that counts how many times a specific element appears in a nested list.

• Requirements:

– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.

– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [ ]:
def count_occurrences(lst, elem):
    count = 0  #initialize counter

    for item in lst:
        if isinstance(item, list):  #check if the item is a nested list
            count += count_occurrences(item, elem)  #recursively count in the nested list
        elif item == elem:
            count += 1 #add counter  when item matches the element
    return count

lst = [[1, 2], [2, 3], [2, 4]]
elem = 2
occourance = count_occurrences(lst, elem)

print("Original List:",lst)
print("Element:",elem)
print("Occourance:",occourance)

Original List: [[1, 2], [2, 3], [2, 4]]
Element: 2
Occourance: 3


7. Flatten a List of Lists of Lists:

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

• Requirements:

– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.

– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst):
    flattened_list = []  #initialize empty list

    for item in lst:
        if isinstance(item, list):
            flattened_list.extend(deep_flatten(item))  #recursively flatten nested list
        else:
            flattened_list.append(item)  #append non-list elements

    return flattened_list

nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
flattened_list = deep_flatten(nested_list)

print("Original Nested List:",nested_list)
print("Flattened List:",flattened_list)

Original Nested List: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Flattened List: [1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:

Write a Python function that calculates the average of all elements in a nested list.

• Requirements:

– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.

– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def average_nested(lst):
    def flatten(lst):
        #function to flatten the nested list
        flattened_list = [] #initialize empty lisrt
        for item in lst:
            if isinstance(item, list):
                flattened_list.extend(flatten(item))  #recursively flatten the list
            else:
                flattened_list.append(item)
        return flattened_list

    flat_list = flatten(lst)  #flatten the nested list
    return sum(flat_list) / len(flat_list) if flat_list else 0  #calculate average element

nested_list = [[1, 2], [3, 4], [5, 6]]
average_element = average_nested(nested_list)

print("Original Nested List:",nested_list)
print("Average Element:",average_element)

Original Nested List: [[1, 2], [3, 4], [5, 6]]
Average Element: 3.5


# 4. Basic Vector and Matrix Operation with Numpy.

## Problem - 1: Array Creation:

1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

In [ ]:
# 1. Initialize an empty array with size 2X2
empty_array = np.empty((2, 2))
print("Empty Array (2x2):\n", empty_array)

Empty Array (2x2):
 [[4.20188005e-316 0.00000000e+000]
 [2.22809558e-312 2.46151512e-312]]


In [ ]:
# 2. Initialize an all-one array with size 4X2
ones_array = np.ones((4, 2))
print("All Ones Array (4x2):\n", ones_array)

All Ones Array (4x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# 3. Return a new array of given shape and type, filled with a specified fill value
fill_value_array = np.full((3, 3), 2)
print("Filled Array (3x3):\n", fill_value_array)

Filled Array (3x3):
 [[2 2 2]
 [2 2 2]
 [2 2 2]]


In [ ]:
# 4. Return a new array of zeros with the same shape and type as a given array
array = np.array([[1, 2, 3], [4, 5, 6]])
zero_array = np.zeros_like(array)
print("Original Array:\n", array)
print("Array of Zeros:\n", zero_array)

Original Array:
 [[1 2 3]
 [4 5 6]]
Array of Zeros:
 [[0 0 0]
 [0 0 0]]


In [ ]:
# 5. Return a new array of ones with the same shape and type as a given array
ones_array = np.ones_like(array)
print("Original Array:\n", array)
print("Array of Ones:\n", ones_array)

Original Array:
 [[1 2 3]
 [4 5 6]]
Array of Ones:
 [[1 1 1]
 [1 1 1]]


In [ ]:
# 6. Convert an existing list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("Converted NumPy Array:\n", numpy_array)

Converted NumPy Array:
 [1 2 3 4]


## Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [39]:
# 1. Create an array with values ranging from 10 to 49
array = np.arange(10, 50)
print("Array 10-49: ")
print(array)

Array 10-49: 
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [40]:
# 2. Create a 3X3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3, 3)
print("3x3 Matrix:")
print(matrix)

3x3 Matrix:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [41]:
# 3. Create a 3X3 identity matrix
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:")
print(identity_matrix)

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [42]:
# 4. Create a random array of size 30 and find the mean of the array
random_array = np.random.random(30)
mean_value = random_array.mean()
print("Random Array:")
print(random_array)
print("Mean of the Array:", mean_value)

Random Array:
[0.9638975  0.64619352 0.51631565 0.12489203 0.95150326 0.08935293
 0.70611803 0.93573656 0.38051917 0.06210225 0.95663513 0.20836389
 0.71941082 0.45756753 0.69294181 0.10221482 0.61897176 0.98943371
 0.14071428 0.56835323 0.07850192 0.78087768 0.91494664 0.72662314
 0.43891308 0.81914446 0.56884772 0.44489232 0.60804673 0.39434164]
Mean of the Array: 0.5535457738651612


In [43]:
# 5. Create a 10X10 array with random values and find the minimum and maximum values
random_array = np.random.random((10, 10))
min_value = random_array.min()
max_value = random_array.max()
print(random_array)
print(f"Minimum value: {min_value}, Maximum value: {max_value}")

[[5.59574030e-01 3.28254103e-01 4.41234097e-01 2.71519045e-01
  8.81927708e-01 1.49317995e-01 9.53900559e-01 5.00041810e-01
  3.12921882e-01 9.74984980e-01]
 [7.91166505e-01 7.97049079e-01 3.91271690e-01 1.13843676e-01
  8.37567802e-01 3.31004178e-01 4.46192675e-01 5.39954798e-02
  1.15025832e-01 2.65372209e-01]
 [2.56388485e-01 6.75872811e-01 9.10710109e-01 6.32260325e-01
  3.48695012e-01 8.97308970e-01 8.88508233e-01 1.53046569e-01
  7.06350582e-01 8.86830349e-01]
 [5.17644111e-04 2.52719353e-01 2.41537206e-01 7.76967663e-02
  2.81379891e-01 6.93929238e-01 5.23787207e-01 3.39079616e-01
  4.10898137e-01 5.16488784e-01]
 [9.58018839e-01 2.48174528e-01 4.08564921e-01 3.72289716e-01
  1.98329245e-02 4.99533235e-01 9.72882210e-02 8.68338233e-01
  1.39091349e-01 6.75907472e-01]
 [8.89240936e-01 4.25206749e-01 2.24814463e-01 3.98811472e-02
  9.29584706e-01 1.48737371e-01 8.71115159e-01 7.98386675e-01
  5.45203356e-01 8.56423791e-03]
 [1.11324265e-01 8.44740178e-01 5.59366999e-01 7.77198696e

In [44]:
# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1
print(zero_array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [45]:
# 7. Reverse an array arr = [1, 2, 0, 0, 4, 0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print(reversed_arr)

[0 4 0 0 2 1]


In [46]:
# 8. Create a 2d array with 1 on border and 0 inside
array = np.ones((5, 5))
array[1:-1, 1:-1] = 0
print(array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [47]:
# 9. Create an 8X8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("Checkerboard pattern:")
print(checkerboard)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Problem - 3: Array Operations:

For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [38]:
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

#Add the two array.
add_result = x + y
print("Addition of x and y:")
print(add_result)

# 2. Subtract the two arrays
subtract_result = x - y
print("\nSubtraction of x and y:")
print(subtract_result)

# 3. Multiply the array with any integers of your choice (e.g., multiply x by 2)
multiply_result = x * 2
print("\nMultiplication of x by 2:")
print(multiply_result)

# 4. Find the square of each element of the array
square_res = np.square(x)
print("\nSquare of each element in x:")
print(square_res)

# 5. Find the dot product between v and w:
dot_vw = np.dot(v,w)
print("\nDot product of v and w:")
print(dot_vw)

dot_xv = np.dot(x,v)
print("\nDot product of x and v:")
print(dot_xv)

dot_xy = np.dot(x,y)
print("\nDot product of x and y:")
print(dot_xy)

# Concatenate x(and)y along row and Concatenate v(and)w along column.
conc_xy = np.concatenate((x,y), axis=0)
print("\nConcatenation of x and y along rows:")
print(conc_xy)

conc_vw = np.concatenate((v.reshape(-1,1),w.reshape(-1,1)), axis=1)
print("\nConcatenation of v and w along column:")
print(conc_vw)

# 7. Concatenate x and v; if you get an error, observe and explain why you got the error?
try:
  concat_xv = np.concatenate((x,v), axis=0)
  print("\n COncatenate x and v along row: ")
  print(concat_xv)
except ValueError as e:
  print(f"Error: {e}")

Addition of x and y:
[[ 6  8]
 [10 13]]

Subtraction of x and y:
[[-4 -4]
 [-4 -3]]

Multiplication of x by 2:
[[ 2  4]
 [ 6 10]]

Square of each element in x:
[[ 1  4]
 [ 9 25]]

Dot product of v and w:
219

Dot product of x and v:
[29 77]

Dot product of x and y:
[[19 22]
 [50 58]]

Concatenation of x and y along rows:
[[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of v and w along column:
[[ 9 11]
 [10 12]]
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


## Problem - 4: Matrix Operations:

• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [48]:
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A−1 = I
A_inv = np.linalg.inv(A)
I = np.dot(A, A_inv)
print("I:")
print(I)

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:")
print(AB)
print("\nBA:")
print(BA)

# 3. Prove (AB)^T = B^T * A^T
AB_transpose = np.dot(A, B).T
B_transpose = B.T
A_transpose = A.T
B_transpose_A_transpose = np.dot(B_transpose, A_transpose)
print("\n(AB)^T:")
print(AB_transpose)
print("\nB^T * A^T: ")
print(B_transpose_A_transpose)


# Solving the system of linear equations using Inverse Method
# Given system of equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Represent the system in matrix form: AX = B
A_eq = np.array([[2,-3,1], [1,-1,2], [3,1,-1]])
B_eq = np.array([-1,-3,9])

#A (A^-1)
X = np.dot(np.linalg.inv(A_eq), B_eq)
print("\nSolution for x, y,z: ")
print(X)



I:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
[[23 13]
 [51 29]]

BA:
[[36 44]
 [13 16]]

(AB)^T:
[[23 51]
 [13 29]]

B^T * A^T: 
[[23 51]
 [13 29]]

Solution for x, y,z: 
[ 2.  1. -2.]
